### ISSUE TITLE
CustomActivityOnCrash.java line 370 cat.ereza.customactivityoncrash.CustomActivityOnCrash.restartApplicationWithIntent

### ISSUE THREAD

**Issue by MrChriZ** [Ereza/CustomActivityOnCrash#64]
Anyone seen this before - I'm picking it up from Crashlytics:
It appears to be crashing trying to restart the main activity in CustomActivityOnCrash.java line 370
cat.ereza.customactivityoncrash.CustomActivityOnCrash.restartApplicationWithIntent

- Raw Text:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.am.TaskRecord.setIntent(com.android.server.am.ActivityRecord)' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1689)
       at android.os.Parcel.readException(Parcel.java:1636)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3159)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1584)
       at android.app.Activity.startActivityForResult(Activity.java:4228)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
       at android.app.Activity.startActivityForResult(Activity.java:4187)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
       at android.app.Activity.startActivity(Activity.java:4515)
       at android.app.Activity.startActivity(Activity.java:4483)
       at cat.ereza.customactivityoncrash.CustomActivityOnCrash.restartApplicationWithIntent(CustomActivityOnCrash.java:370)

Normally the app restarts fine... but occasionally I'm getting this.

**Comment by Ereza** [comment]
As pointed in the referenced issue, it appears to be some kind of issue in the Android OS code... Closing this for now as I think it's unrelated to the library, if you think otherwise and can provide more info, please reopen. Thanks!
