### ISSUE TITLE
Unable to get provider cat.ereza.customactivityoncrash.provider.CaocInitProvider(solved)

### ISSUE THREAD

**Issue by abbasalim** [Ereza/CustomActivityOnCrash#70]
hi, when i run my app in android 4.4 give me this error:

`02-23 04:47:13.981 2752-2752/ir.daneshnamegroup.quran E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ir.daneshnamegroup.quran, PID: 2752
    java.lang.RuntimeException: Unable to get provider cat.ereza.customactivityoncrash.provider.CaocInitProvider: java.lang.ClassNotFoundException: Didn't find class "cat.ereza.customactivityoncrash.provider.CaocInitProvider" on path: DexPathList[[zip file "/data/app/ir.daneshnamegroup.quran-1.apk"],nativeLibraryDirectories=[/data/app-lib/ir.daneshnamegroup.quran-1, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4777)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4369)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4309)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "cat.ereza.customactivityoncrash.provider.CaocInitProvider" on path: DexPathList[[zip file "/data/app/ir.daneshnamegroup.quran-1.apk"],nativeLibraryDirectories=[/data/app-lib/ir.daneshnamegroup.quran-1, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)`

**Comment by abbasalim** [comment]
solved by replace  `extends Application`   with `extends MultiDexApplication `
