### ISSUE TITLE
OutOfMemoryError: pthread_create

### ISSUE THREAD

**Issue by hoordev** [Ereza/CustomActivityOnCrash#72]
**Report by Firebase**

Brand: Xiaomi
Model: Redmi 6A
Orientation: Portrait
RAM free: 700.47 MB
Disk free: 858.34 MB

Androdi Version: 9
Orientation: Portrait
Rooted: No

LargeHeap enabled in manifest: true

`Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:733)
       at android.app.SharedPreferencesImpl.startLoadFromDisk(SharedPreferencesImpl.java:124)
       at android.app.SharedPreferencesImpl.<init>(SharedPreferencesImpl.java:113)
       at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:434)
       at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:415)
       at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:184)
       at cat.ereza.customactivityoncrash.CustomActivityOnCrash.getLastCrashTimestamp(CustomActivityOnCrash.java:696)
       at cat.ereza.customactivityoncrash.CustomActivityOnCrash.hasCrashedInTheLastSeconds(CustomActivityOnCrash.java:706)
       at cat.ereza.customactivityoncrash.CustomActivityOnCrash.access$200(CustomActivityOnCrash.java:56)
       at cat.ereza.customactivityoncrash.CustomActivityOnCrash$1.uncaughtException(CustomActivityOnCrash.java:118)
       at com.google.firebase.crashlytics.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:58)
       at org.chromium.base.JavaExceptionReporter.uncaughtException(JavaExceptionReporter.java:6)
       at com.facebook.internal.instrument.crashreport.CrashHandler.uncaughtException(CrashHandler.java:65)
       at com.google.android.gms.analytics.ExceptionReporter.uncaughtException(ExceptionReporter.java:37)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
       at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImplKt.java:33)
       at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandlerKt.java:33)
       at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.java:95)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:64)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6820)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)`

**Comment by Ereza** [comment]
Can you provide more details about this issue? Can you reproduce it in any way? OOM can happen everywhere...

**Comment by Ereza** [comment]
Closing due to inactivity.
