### ISSUE TITLE
App is get Crash on launch

### ISSUE THREAD

**Issue by rahul-kumawat-vts** [Ereza/CustomActivityOnCrash#99]
We have used this setWebContentsDebuggingEnabled(true) to enable the debugging of webview. We are getting crash on firebase after this. 

library version : cat.ereza:customactivityoncrash:2.3.0

<img width="667" alt="Screenshot 2024-05-15 at 6 24 02 PM" src="https://github.com/Ereza/CustomActivityOnCrash/assets/95904537/2def1a7d-abb2-466d-99fe-53133d099566">

```
Fatal Exception: java.lang.RuntimeException: Unable to create application com.risesoftware.riseliving.AnalyticsApplication: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.risesoftware.riseliving (pid 344), lock owner com.risesoftware.riseliving:error_activity (pid 26922)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7609)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8747)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

`Caused by java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.risesoftware.riseliving (pid 344), lock owner com.risesoftware.riseliving:error_activity (pid 26922)
       at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle6432.aab-stable-631204033:201)
       at org.chromium.android_webview.AwBrowserProcess.j(chromium-TrichromeWebViewGoogle6432.aab-stable-631204033:15)
       at com.android.webview.chromium.E.d(chromium-TrichromeWebViewGoogle6432.aab-stable-631204033:188)
       at com.android.webview.chromium.E.b(chromium-TrichromeWebViewGoogle6432.aab-stable-631204033:42)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(chromium-TrichromeWebViewGoogle6432.aab-stable-631204033:16)
       at android.webkit.WebView.setWebContentsDebuggingEnabled(WebView.java:2014)
       at com.risesoftware.riseliving.App.onCreate(App.java:149)
       at com.risesoftware.riseliving.AnalyticsApplication.onCreate(AnalyticsApplication.kt:10)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7604)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8747)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by vanzar-codigo** [comment]
Having same issue in 2.3.0
```
          Fatal Exception: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.fwd.codigo (pid 20047), lock owner com.fwd.codigo:error_activity (pid 4928)
       at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle6432.aab-stable-720415733:195)
       at org.chromium.android_webview.AwBrowserProcess.e(chromium-TrichromeWebViewGoogle6432.aab-stable-720415733:16)
       at WV.i80.run(chromium-TrichromeWebViewGoogle6432.aab-stable-720415733:188)
       at WV.j80.run(chromium-TrichromeWebViewGoogle6432.aab-stable-720415733:24)
       at WV.o80.b(chromium-TrichromeWebViewGoogle6432.aab-stable-720415733:7)
       at com.android.webview.chromium.O.e(chromium-TrichromeWebViewGoogle6432.aab-stable-720415733:108)
       at WV.k80.run(chromium-TrichromeWebViewGoogle6432.aab-stable-720415733:25)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:342)
       at android.app.ActivityThread.main(ActivityThread.java:9638)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:619)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
        
```
